windowrule {
    name = "kitty" 
    match:class = ^(kitty)$
    float = true
    center = true
    size = 1400 900
}

windowrule {
    name = "Nautilus"
    match:class = ^(org.gnome.Nautilus)$
    float = true
    move = 170 130
    size = 1350 750
    opacity = 0.90
}

windowrule {
    name = "WhatsApp"
    match:class = ^(elecwhat)$
    float = true
    center = true
    size = 1400 900
    opacity = 0.97
}

windowrule {
    name = "Spotify"
    match:class = ^(spotify)$
    float = true
    move = 60 60
    size = 1500 900
    opacity = 0.90
}

windowrule {
    name = "MissionCenter"
    match:class = ^(io.missioncenter.MissionCenter)$
    float = true
    size = 1100 650
    move = 60 60
}

windowrule {
    name = "Transmission"
    match:class = ^(com.transmissionbt.transmission_66306_15075203)$
    center = true
    float = true
    size = 1000 600
}

windowrule {
    name = "Vivaldi"
    match:class = ^(vivaldi-stable)$
    center = true
    float = true
    opacity = 0.95
    size = 1700 950
}


windowrule {
    name = "Obsidian"
    match:class = ^(obsidian)$
    float = true
    move = 400 100
    size = 1400 900
}

windowrule {
    name = "figma"
    match:class = ^(figma-linux)$
    float = true
    size =1800 800
    opacity = 1.1
}

windowrule {
    name = "OBS"
    match:class = ^(com.obsproject.Studio)$
    float = true
    move = 60 60 
    size = 1200 700
}

windowrule {
    name = "Shotwell_Pictures"
    match:class = ^(org.gnome.Shotwell)$
    float = true
    move = 60 60 
    size = 1200 700
}

windowrule {
    name = "Vscode"
    match:class = ^(code)$
    float = true
    move = 60 60 
    opacity = 0.90
    size = 1700 800
}

windowrule {
    name = "Matplotlib"
    match:class = ^(Matplotlib)$
    float = true
    move = 60 60 
    size = 1700 800
}

windowrule {
    name = "Discord"
    match:class = ^(discord)$
    float = true
    size = 1450 950
}


windowrule {
    name = "Edge"
    match:class = ^(microsoft-edge)$
    float = true
    size = 1000 990
    opacity = 1.1
    move = 100 50
}

