source = ~/.config/hypr/colors.conf                           # Include colors settings
source = ~/.config/hypr/configs/auto_start.conf               # Include Autostart settings
source = ~/.config/hypr/configs/keybinding.conf               # Include keybinding
source = ~/.config/hypr/configs/monitors.conf                 # Include appearance settings
source = ~/.config/hypr/configs/variables.conf                # Include apps settings
source = ~/.config/hypr/configs/visuals.conf                  # Include apps settings
source = ~/.config/hypr/configs/monitors.conf                 # Include monitor settings
source = ~/.config/hypr/configs/windowrules.conf              # Include window rules
source = ~/.config/hypr/configs/gestures.conf                 # Include gesture  settings

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true 
}

